accounts:
  - name: alice
    mnemonic: "slide moment original seven milk crawl help text kick fluid boring awkward doll wonder sure fragile plate grid hard next casual expire okay body"
    coins: ["200000000uspn"]
  - name: bob
    mnemonic: "trap possible liquid elite embody host segment fantasy swim cable digital eager tiny broom burden diary earn hen grow engine pigeon fringe claim program"
    coins: ["200000000uspn"]
validator:
  name: alice
  staked: "100000000uspn"
faucet:
  name: bob
  coins: ["100000uspn"]
  port: 4502
genesis:
  chain_id: spn-1
  app_state:
    staking:
      params:
        bond_denom: "uspn"
    crisis:
      constant_fee:
        denom: "uspn"
    gov:
      deposit_params:
        min_deposit:
          - "amount": "1"
            "denom": "uspn"
    mint:
      params:
        mint_denom: "uspn"
        distribution_proportions:
          staking: "0.300000000000000000"
          incentives: "0.400000000000000000"
          development_fund: "0.200000000000000000"
          community_pool: "0.100000000000000000"
        development_fund_recipients:
          - address: "spn1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul" # alice
            weight: "0.400000000000000000"
          - address: "spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe" # bob
            weight: "0.300000000000000000"
          - address: "spn1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5" # carol
            weight: "0.300000000000000000"
    launch:
      params:
        revertDelay: "5"
        launchTimeRange:
          minLaunchTime: "5"
    fundraising:
      params:
        auction_creation_fee:
          - amount: "100"
            denom: "uspn"
    monitoringp:
      params:
        lastBlockHeight: "1"
        consumerChainID: "orbit-1"
        consumerUnbondingPeriod: "2"
        consumerRevisionHeight: "1"
    participation:
      params:
        allocationPrice:
          bonded: "1000"
        participationTierList:
          - tierID: "1"
            requiredAllocations: "1"
            benefits:
              maxBidAmount: "1000"
          - tierID: "2"
            requiredAllocations: "2"
            benefits:
              maxBidAmount: "2000"
          - tierID: "3"
            requiredAllocations: "5"
            benefits:
              maxBidAmount: "10000"
          - tierID: "4"
            requiredAllocations: "10"
            benefits:
              maxBidAmount: "30000"
        # represents 1/3 of the default unbonding period (21 days): one week
        registrationPeriod: "604800s"
        # represents 2/3 of the default unbonding period (21 days): two weeks
        withdrawalDelay: "1209600s"
client:
  typescript:
    path: "ignite-ui/src/generated"
host:
  rpc: ":26661"
  p2p: ":26660"
  prof: ":6062"
  grpc: ":9094"
  grpc-web: ":9095"
  api: ":1319"