---
- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:
    - name: ensure all disks are mounted
      shell: mount -a
      args:
        warn: no
    - name: add spn user
      user:
        name: spn
        shell: /bin/bash
    - name: fix ownership and permissions
      file:
        path: /home/spn
        state: directory
        recurse: yes
        owner: spn
        group: spn
    - name: install acl
      apt:
        name: acl
        update_cache: yes
    - name: install Go
      snap:
        name: go
        classic: yes
    - name: clone spn repo
      git:
        repo: https://github.com/tendermint/spn.git
        dest: /usr/local/src/spn
    - name: build spn
      args:
        chdir: /usr/local/src/spn
        executable: /bin/bash
      shell: go build -o /usr/local/bin/spnd ./cmd/spnd

- hosts: all
  become: yes
  remote_user: ubuntu
  vars:
    app_name: spn
    data_dir: .spn
    reset: "true"
    chain_id: spn
    validators_assets: 100000000000000000000stake,100000000000000000000token
    generate_faucet_account: 100000000000000000000token
  roles:
    - cosmos-node
