// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spn/profile/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateValidatorDescription struct {
	Address     string               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Description ValidatorDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description"`
}

func (m *MsgUpdateValidatorDescription) Reset()         { *m = MsgUpdateValidatorDescription{} }
func (m *MsgUpdateValidatorDescription) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateValidatorDescription) ProtoMessage()    {}
func (*MsgUpdateValidatorDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{0}
}
func (m *MsgUpdateValidatorDescription) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateValidatorDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateValidatorDescription.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateValidatorDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateValidatorDescription.Merge(m, src)
}
func (m *MsgUpdateValidatorDescription) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateValidatorDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateValidatorDescription.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateValidatorDescription proto.InternalMessageInfo

func (m *MsgUpdateValidatorDescription) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgUpdateValidatorDescription) GetDescription() ValidatorDescription {
	if m != nil {
		return m.Description
	}
	return ValidatorDescription{}
}

type MsgUpdateValidatorDescriptionResponse struct {
}

func (m *MsgUpdateValidatorDescriptionResponse) Reset()         { *m = MsgUpdateValidatorDescriptionResponse{} }
func (m *MsgUpdateValidatorDescriptionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateValidatorDescriptionResponse) ProtoMessage()    {}
func (*MsgUpdateValidatorDescriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{1}
}
func (m *MsgUpdateValidatorDescriptionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateValidatorDescriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateValidatorDescriptionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateValidatorDescriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateValidatorDescriptionResponse.Merge(m, src)
}
func (m *MsgUpdateValidatorDescriptionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateValidatorDescriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateValidatorDescriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateValidatorDescriptionResponse proto.InternalMessageInfo

type MsgAddValidatorOperatorAddress struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	OperatorAddress  string `protobuf:"bytes,2,opt,name=operatorAddress,proto3" json:"operatorAddress,omitempty"`
}

func (m *MsgAddValidatorOperatorAddress) Reset()         { *m = MsgAddValidatorOperatorAddress{} }
func (m *MsgAddValidatorOperatorAddress) String() string { return proto.CompactTextString(m) }
func (*MsgAddValidatorOperatorAddress) ProtoMessage()    {}
func (*MsgAddValidatorOperatorAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{2}
}
func (m *MsgAddValidatorOperatorAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddValidatorOperatorAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddValidatorOperatorAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddValidatorOperatorAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddValidatorOperatorAddress.Merge(m, src)
}
func (m *MsgAddValidatorOperatorAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddValidatorOperatorAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddValidatorOperatorAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddValidatorOperatorAddress proto.InternalMessageInfo

func (m *MsgAddValidatorOperatorAddress) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *MsgAddValidatorOperatorAddress) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

type MsgAddValidatorOperatorAddressResponse struct {
}

func (m *MsgAddValidatorOperatorAddressResponse) Reset() {
	*m = MsgAddValidatorOperatorAddressResponse{}
}
func (m *MsgAddValidatorOperatorAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddValidatorOperatorAddressResponse) ProtoMessage()    {}
func (*MsgAddValidatorOperatorAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{3}
}
func (m *MsgAddValidatorOperatorAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddValidatorOperatorAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddValidatorOperatorAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddValidatorOperatorAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddValidatorOperatorAddressResponse.Merge(m, src)
}
func (m *MsgAddValidatorOperatorAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddValidatorOperatorAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddValidatorOperatorAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddValidatorOperatorAddressResponse proto.InternalMessageInfo

type MsgCreateCoordinator struct {
	Address     string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Description CoordinatorDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description"`
}

func (m *MsgCreateCoordinator) Reset()         { *m = MsgCreateCoordinator{} }
func (m *MsgCreateCoordinator) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCoordinator) ProtoMessage()    {}
func (*MsgCreateCoordinator) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{4}
}
func (m *MsgCreateCoordinator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCoordinator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCoordinator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCoordinator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCoordinator.Merge(m, src)
}
func (m *MsgCreateCoordinator) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCoordinator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCoordinator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCoordinator proto.InternalMessageInfo

func (m *MsgCreateCoordinator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgCreateCoordinator) GetDescription() CoordinatorDescription {
	if m != nil {
		return m.Description
	}
	return CoordinatorDescription{}
}

type MsgCreateCoordinatorResponse struct {
	CoordinatorID uint64 `protobuf:"varint,1,opt,name=coordinatorID,proto3" json:"coordinatorID,omitempty"`
}

func (m *MsgCreateCoordinatorResponse) Reset()         { *m = MsgCreateCoordinatorResponse{} }
func (m *MsgCreateCoordinatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCoordinatorResponse) ProtoMessage()    {}
func (*MsgCreateCoordinatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{5}
}
func (m *MsgCreateCoordinatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCoordinatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCoordinatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCoordinatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCoordinatorResponse.Merge(m, src)
}
func (m *MsgCreateCoordinatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCoordinatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCoordinatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCoordinatorResponse proto.InternalMessageInfo

func (m *MsgCreateCoordinatorResponse) GetCoordinatorID() uint64 {
	if m != nil {
		return m.CoordinatorID
	}
	return 0
}

type MsgUpdateCoordinatorDescription struct {
	Address     string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Description CoordinatorDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description"`
}

func (m *MsgUpdateCoordinatorDescription) Reset()         { *m = MsgUpdateCoordinatorDescription{} }
func (m *MsgUpdateCoordinatorDescription) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCoordinatorDescription) ProtoMessage()    {}
func (*MsgUpdateCoordinatorDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{6}
}
func (m *MsgUpdateCoordinatorDescription) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCoordinatorDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCoordinatorDescription.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCoordinatorDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCoordinatorDescription.Merge(m, src)
}
func (m *MsgUpdateCoordinatorDescription) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCoordinatorDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCoordinatorDescription.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCoordinatorDescription proto.InternalMessageInfo

func (m *MsgUpdateCoordinatorDescription) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgUpdateCoordinatorDescription) GetDescription() CoordinatorDescription {
	if m != nil {
		return m.Description
	}
	return CoordinatorDescription{}
}

type MsgUpdateCoordinatorDescriptionResponse struct {
}

func (m *MsgUpdateCoordinatorDescriptionResponse) Reset() {
	*m = MsgUpdateCoordinatorDescriptionResponse{}
}
func (m *MsgUpdateCoordinatorDescriptionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCoordinatorDescriptionResponse) ProtoMessage()    {}
func (*MsgUpdateCoordinatorDescriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{7}
}
func (m *MsgUpdateCoordinatorDescriptionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCoordinatorDescriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCoordinatorDescriptionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCoordinatorDescriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCoordinatorDescriptionResponse.Merge(m, src)
}
func (m *MsgUpdateCoordinatorDescriptionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCoordinatorDescriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCoordinatorDescriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCoordinatorDescriptionResponse proto.InternalMessageInfo

type MsgUpdateCoordinatorAddress struct {
	Address    string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewAddress string `protobuf:"bytes,2,opt,name=newAddress,proto3" json:"newAddress,omitempty"`
}

func (m *MsgUpdateCoordinatorAddress) Reset()         { *m = MsgUpdateCoordinatorAddress{} }
func (m *MsgUpdateCoordinatorAddress) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCoordinatorAddress) ProtoMessage()    {}
func (*MsgUpdateCoordinatorAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{8}
}
func (m *MsgUpdateCoordinatorAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCoordinatorAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCoordinatorAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCoordinatorAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCoordinatorAddress.Merge(m, src)
}
func (m *MsgUpdateCoordinatorAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCoordinatorAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCoordinatorAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCoordinatorAddress proto.InternalMessageInfo

func (m *MsgUpdateCoordinatorAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgUpdateCoordinatorAddress) GetNewAddress() string {
	if m != nil {
		return m.NewAddress
	}
	return ""
}

type MsgUpdateCoordinatorAddressResponse struct {
}

func (m *MsgUpdateCoordinatorAddressResponse) Reset()         { *m = MsgUpdateCoordinatorAddressResponse{} }
func (m *MsgUpdateCoordinatorAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCoordinatorAddressResponse) ProtoMessage()    {}
func (*MsgUpdateCoordinatorAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{9}
}
func (m *MsgUpdateCoordinatorAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCoordinatorAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCoordinatorAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCoordinatorAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCoordinatorAddressResponse.Merge(m, src)
}
func (m *MsgUpdateCoordinatorAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCoordinatorAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCoordinatorAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCoordinatorAddressResponse proto.InternalMessageInfo

type MsgDisableCoordinator struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgDisableCoordinator) Reset()         { *m = MsgDisableCoordinator{} }
func (m *MsgDisableCoordinator) String() string { return proto.CompactTextString(m) }
func (*MsgDisableCoordinator) ProtoMessage()    {}
func (*MsgDisableCoordinator) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{10}
}
func (m *MsgDisableCoordinator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableCoordinator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableCoordinator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableCoordinator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableCoordinator.Merge(m, src)
}
func (m *MsgDisableCoordinator) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableCoordinator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableCoordinator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableCoordinator proto.InternalMessageInfo

func (m *MsgDisableCoordinator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgDisableCoordinatorResponse struct {
	CoordinatorID uint64 `protobuf:"varint,1,opt,name=coordinatorID,proto3" json:"coordinatorID,omitempty"`
}

func (m *MsgDisableCoordinatorResponse) Reset()         { *m = MsgDisableCoordinatorResponse{} }
func (m *MsgDisableCoordinatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDisableCoordinatorResponse) ProtoMessage()    {}
func (*MsgDisableCoordinatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_227b73a1f63bc900, []int{11}
}
func (m *MsgDisableCoordinatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableCoordinatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableCoordinatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableCoordinatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableCoordinatorResponse.Merge(m, src)
}
func (m *MsgDisableCoordinatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableCoordinatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableCoordinatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableCoordinatorResponse proto.InternalMessageInfo

func (m *MsgDisableCoordinatorResponse) GetCoordinatorID() uint64 {
	if m != nil {
		return m.CoordinatorID
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgUpdateValidatorDescription)(nil), "spn.profile.MsgUpdateValidatorDescription")
	proto.RegisterType((*MsgUpdateValidatorDescriptionResponse)(nil), "spn.profile.MsgUpdateValidatorDescriptionResponse")
	proto.RegisterType((*MsgAddValidatorOperatorAddress)(nil), "spn.profile.MsgAddValidatorOperatorAddress")
	proto.RegisterType((*MsgAddValidatorOperatorAddressResponse)(nil), "spn.profile.MsgAddValidatorOperatorAddressResponse")
	proto.RegisterType((*MsgCreateCoordinator)(nil), "spn.profile.MsgCreateCoordinator")
	proto.RegisterType((*MsgCreateCoordinatorResponse)(nil), "spn.profile.MsgCreateCoordinatorResponse")
	proto.RegisterType((*MsgUpdateCoordinatorDescription)(nil), "spn.profile.MsgUpdateCoordinatorDescription")
	proto.RegisterType((*MsgUpdateCoordinatorDescriptionResponse)(nil), "spn.profile.MsgUpdateCoordinatorDescriptionResponse")
	proto.RegisterType((*MsgUpdateCoordinatorAddress)(nil), "spn.profile.MsgUpdateCoordinatorAddress")
	proto.RegisterType((*MsgUpdateCoordinatorAddressResponse)(nil), "spn.profile.MsgUpdateCoordinatorAddressResponse")
	proto.RegisterType((*MsgDisableCoordinator)(nil), "spn.profile.MsgDisableCoordinator")
	proto.RegisterType((*MsgDisableCoordinatorResponse)(nil), "spn.profile.MsgDisableCoordinatorResponse")
}

func init() { proto.RegisterFile("spn/profile/tx.proto", fileDescriptor_227b73a1f63bc900) }

var fileDescriptor_227b73a1f63bc900 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4d, 0x6e, 0xd3, 0x40,
	0x14, 0xce, 0x40, 0x01, 0xf5, 0x45, 0x08, 0xb0, 0x82, 0x14, 0x9c, 0xd6, 0x6d, 0x5d, 0x4a, 0x93,
	0x00, 0x09, 0x4a, 0xb9, 0x40, 0x7e, 0x58, 0x54, 0x95, 0x85, 0x64, 0x04, 0x0b, 0x36, 0xc8, 0xc9,
	0x0c, 0xc6, 0x52, 0xe2, 0x31, 0x33, 0x43, 0x28, 0x12, 0x12, 0x12, 0x27, 0x60, 0xc7, 0x8e, 0x05,
	0x67, 0xe0, 0x10, 0x15, 0xab, 0x8a, 0x15, 0x2b, 0x84, 0x92, 0x8b, 0xa0, 0x38, 0xf6, 0xc4, 0x8e,
	0x8d, 0xdd, 0x94, 0x05, 0xab, 0xc4, 0xef, 0x7d, 0xf3, 0xbe, 0xef, 0xfd, 0xcd, 0x40, 0x89, 0x7b,
	0x6e, 0xd3, 0x63, 0xf4, 0xa5, 0x33, 0x24, 0x4d, 0x71, 0xdc, 0xf0, 0x18, 0x15, 0x54, 0x29, 0x72,
	0xcf, 0x6d, 0x04, 0x56, 0xb5, 0x64, 0x53, 0x9b, 0xfa, 0xf6, 0xe6, 0xec, 0xdf, 0x1c, 0xa2, 0xde,
	0x1a, 0x50, 0x3e, 0xa2, 0xfc, 0xc5, 0xdc, 0x31, 0xff, 0x08, 0x5c, 0x9b, 0xd1, 0x98, 0x03, 0x4a,
	0x19, 0x76, 0x5c, 0x4b, 0x50, 0x16, 0xb8, 0x2b, 0x51, 0xf7, 0xd8, 0x1a, 0x3a, 0x78, 0xe1, 0xd4,
	0xbf, 0x20, 0xd8, 0x34, 0xb8, 0xfd, 0xd4, 0xc3, 0x96, 0x20, 0xcf, 0x42, 0x67, 0x8f, 0xf0, 0x01,
	0x73, 0x3c, 0xe1, 0x50, 0x57, 0x69, 0xc1, 0x15, 0x0b, 0x63, 0x46, 0x38, 0x2f, 0xa3, 0x6d, 0x54,
	0x5d, 0xef, 0x94, 0x7f, 0x7c, 0xbb, 0x5f, 0x0a, 0x04, 0xb4, 0xe7, 0x9e, 0x27, 0x82, 0x39, 0xae,
	0x6d, 0x86, 0x40, 0xe5, 0x10, 0x8a, 0x78, 0x11, 0xa2, 0x7c, 0x61, 0x1b, 0x55, 0x8b, 0xad, 0x9d,
	0x46, 0x24, 0xcb, 0x46, 0x1a, 0x57, 0x67, 0xed, 0xe4, 0xd7, 0x56, 0xc1, 0x8c, 0x9e, 0xd5, 0xf7,
	0x61, 0x2f, 0x53, 0x9f, 0x49, 0xb8, 0x47, 0x5d, 0x4e, 0xf4, 0x31, 0x68, 0x06, 0xb7, 0xdb, 0x18,
	0x4b, 0xd4, 0x63, 0x8f, 0xb0, 0xd9, 0x6f, 0x20, 0x52, 0xa9, 0xc3, 0x75, 0x99, 0x7e, 0x3b, 0x9a,
	0x92, 0x99, 0xb0, 0x2b, 0x55, 0xb8, 0x46, 0xe3, 0xc7, 0xfd, 0x2c, 0xd6, 0xcd, 0x65, 0xb3, 0x5e,
	0x85, 0x3b, 0xd9, 0xbc, 0x52, 0xe1, 0x67, 0x04, 0x25, 0x83, 0xdb, 0x5d, 0x46, 0x2c, 0x41, 0xba,
	0x8b, 0x3e, 0x9d, 0xab, 0xc4, 0x47, 0x69, 0x25, 0xde, 0x8d, 0x95, 0x38, 0x42, 0x91, 0x53, 0xe4,
	0x1e, 0x6c, 0xa4, 0x09, 0x0b, 0x95, 0x2b, 0xb7, 0xe1, 0x6a, 0x64, 0xae, 0x0e, 0x7b, 0xbe, 0xcc,
	0x35, 0x33, 0x6e, 0xd4, 0xbf, 0x22, 0xd8, 0x92, 0xbd, 0x4a, 0x27, 0xff, 0xff, 0xa9, 0xd6, 0x60,
	0x3f, 0x47, 0xa3, 0xec, 0xd7, 0x6b, 0xa8, 0xa4, 0x41, 0xc3, 0x11, 0x39, 0x4f, 0x2a, 0x1a, 0x80,
	0x4b, 0xde, 0xc6, 0x27, 0x2a, 0x62, 0xd1, 0xf7, 0x60, 0x37, 0x83, 0x52, 0x2a, 0x3b, 0x82, 0x9b,
	0x06, 0xb7, 0x7b, 0x0e, 0xb7, 0xfa, 0xc3, 0x7f, 0x9d, 0x24, 0xfd, 0x91, 0x7f, 0x03, 0x24, 0x83,
	0xad, 0xd6, 0xfd, 0xd6, 0xf7, 0x4b, 0x70, 0xd1, 0xe0, 0xb6, 0xf2, 0x1e, 0xd4, 0x8c, 0xdb, 0xa4,
	0x1e, 0x6b, 0x5b, 0xe6, 0x66, 0xab, 0xad, 0xb3, 0x63, 0xa5, 0xd6, 0x0f, 0x50, 0xc9, 0xba, 0x02,
	0xee, 0x2e, 0x87, 0xcc, 0x00, 0xab, 0x07, 0x2b, 0x80, 0xa5, 0x00, 0x0b, 0x6e, 0x24, 0x17, 0x7c,
	0x67, 0x39, 0x52, 0x02, 0xa2, 0xd6, 0x72, 0x21, 0x92, 0xe2, 0x23, 0x82, 0x8d, 0xcc, 0x25, 0xbb,
	0x97, 0x5e, 0xb8, 0x74, 0xb4, 0xfa, 0x70, 0x15, 0xb4, 0x14, 0x31, 0x86, 0xf2, 0x5f, 0x37, 0xa3,
	0x9a, 0x1b, 0x31, 0x2c, 0xf1, 0x83, 0xb3, 0x22, 0x25, 0x2f, 0x06, 0x25, 0x65, 0xee, 0xf5, 0xe5,
	0x38, 0x49, 0x8c, 0x5a, 0xcf, 0xc7, 0x84, 0x2c, 0x9d, 0xee, 0xc9, 0x44, 0x43, 0xa7, 0x13, 0x0d,
	0xfd, 0x9e, 0x68, 0xe8, 0xd3, 0x54, 0x2b, 0x9c, 0x4e, 0xb5, 0xc2, 0xcf, 0xa9, 0x56, 0x78, 0x5e,
	0xb3, 0x1d, 0xf1, 0xea, 0x4d, 0xbf, 0x31, 0xa0, 0xa3, 0xa6, 0x20, 0x2e, 0x26, 0x6c, 0xe4, 0xb8,
	0xa2, 0x39, 0x7b, 0x63, 0x8f, 0x17, 0x0f, 0xfb, 0x3b, 0x8f, 0xf0, 0xfe, 0x65, 0xff, 0x89, 0x3d,
	0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x57, 0xdf, 0xd1, 0xbe, 0xf4, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateValidatorDescription(ctx context.Context, in *MsgUpdateValidatorDescription, opts ...grpc.CallOption) (*MsgUpdateValidatorDescriptionResponse, error)
	AddValidatorOperatorAddress(ctx context.Context, in *MsgAddValidatorOperatorAddress, opts ...grpc.CallOption) (*MsgAddValidatorOperatorAddressResponse, error)
	CreateCoordinator(ctx context.Context, in *MsgCreateCoordinator, opts ...grpc.CallOption) (*MsgCreateCoordinatorResponse, error)
	UpdateCoordinatorDescription(ctx context.Context, in *MsgUpdateCoordinatorDescription, opts ...grpc.CallOption) (*MsgUpdateCoordinatorDescriptionResponse, error)
	UpdateCoordinatorAddress(ctx context.Context, in *MsgUpdateCoordinatorAddress, opts ...grpc.CallOption) (*MsgUpdateCoordinatorAddressResponse, error)
	DisableCoordinator(ctx context.Context, in *MsgDisableCoordinator, opts ...grpc.CallOption) (*MsgDisableCoordinatorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateValidatorDescription(ctx context.Context, in *MsgUpdateValidatorDescription, opts ...grpc.CallOption) (*MsgUpdateValidatorDescriptionResponse, error) {
	out := new(MsgUpdateValidatorDescriptionResponse)
	err := c.cc.Invoke(ctx, "/spn.profile.Msg/UpdateValidatorDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddValidatorOperatorAddress(ctx context.Context, in *MsgAddValidatorOperatorAddress, opts ...grpc.CallOption) (*MsgAddValidatorOperatorAddressResponse, error) {
	out := new(MsgAddValidatorOperatorAddressResponse)
	err := c.cc.Invoke(ctx, "/spn.profile.Msg/AddValidatorOperatorAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCoordinator(ctx context.Context, in *MsgCreateCoordinator, opts ...grpc.CallOption) (*MsgCreateCoordinatorResponse, error) {
	out := new(MsgCreateCoordinatorResponse)
	err := c.cc.Invoke(ctx, "/spn.profile.Msg/CreateCoordinator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCoordinatorDescription(ctx context.Context, in *MsgUpdateCoordinatorDescription, opts ...grpc.CallOption) (*MsgUpdateCoordinatorDescriptionResponse, error) {
	out := new(MsgUpdateCoordinatorDescriptionResponse)
	err := c.cc.Invoke(ctx, "/spn.profile.Msg/UpdateCoordinatorDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCoordinatorAddress(ctx context.Context, in *MsgUpdateCoordinatorAddress, opts ...grpc.CallOption) (*MsgUpdateCoordinatorAddressResponse, error) {
	out := new(MsgUpdateCoordinatorAddressResponse)
	err := c.cc.Invoke(ctx, "/spn.profile.Msg/UpdateCoordinatorAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableCoordinator(ctx context.Context, in *MsgDisableCoordinator, opts ...grpc.CallOption) (*MsgDisableCoordinatorResponse, error) {
	out := new(MsgDisableCoordinatorResponse)
	err := c.cc.Invoke(ctx, "/spn.profile.Msg/DisableCoordinator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateValidatorDescription(context.Context, *MsgUpdateValidatorDescription) (*MsgUpdateValidatorDescriptionResponse, error)
	AddValidatorOperatorAddress(context.Context, *MsgAddValidatorOperatorAddress) (*MsgAddValidatorOperatorAddressResponse, error)
	CreateCoordinator(context.Context, *MsgCreateCoordinator) (*MsgCreateCoordinatorResponse, error)
	UpdateCoordinatorDescription(context.Context, *MsgUpdateCoordinatorDescription) (*MsgUpdateCoordinatorDescriptionResponse, error)
	UpdateCoordinatorAddress(context.Context, *MsgUpdateCoordinatorAddress) (*MsgUpdateCoordinatorAddressResponse, error)
	DisableCoordinator(context.Context, *MsgDisableCoordinator) (*MsgDisableCoordinatorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateValidatorDescription(ctx context.Context, req *MsgUpdateValidatorDescription) (*MsgUpdateValidatorDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateValidatorDescription not implemented")
}
func (*UnimplementedMsgServer) AddValidatorOperatorAddress(ctx context.Context, req *MsgAddValidatorOperatorAddress) (*MsgAddValidatorOperatorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddValidatorOperatorAddress not implemented")
}
func (*UnimplementedMsgServer) CreateCoordinator(ctx context.Context, req *MsgCreateCoordinator) (*MsgCreateCoordinatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCoordinator not implemented")
}
func (*UnimplementedMsgServer) UpdateCoordinatorDescription(ctx context.Context, req *MsgUpdateCoordinatorDescription) (*MsgUpdateCoordinatorDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCoordinatorDescription not implemented")
}
func (*UnimplementedMsgServer) UpdateCoordinatorAddress(ctx context.Context, req *MsgUpdateCoordinatorAddress) (*MsgUpdateCoordinatorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCoordinatorAddress not implemented")
}
func (*UnimplementedMsgServer) DisableCoordinator(ctx context.Context, req *MsgDisableCoordinator) (*MsgDisableCoordinatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableCoordinator not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateValidatorDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateValidatorDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateValidatorDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spn.profile.Msg/UpdateValidatorDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateValidatorDescription(ctx, req.(*MsgUpdateValidatorDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddValidatorOperatorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddValidatorOperatorAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddValidatorOperatorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spn.profile.Msg/AddValidatorOperatorAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddValidatorOperatorAddress(ctx, req.(*MsgAddValidatorOperatorAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCoordinator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spn.profile.Msg/CreateCoordinator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCoordinator(ctx, req.(*MsgCreateCoordinator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCoordinatorDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCoordinatorDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCoordinatorDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spn.profile.Msg/UpdateCoordinatorDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCoordinatorDescription(ctx, req.(*MsgUpdateCoordinatorDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCoordinatorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCoordinatorAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCoordinatorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spn.profile.Msg/UpdateCoordinatorAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCoordinatorAddress(ctx, req.(*MsgUpdateCoordinatorAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableCoordinator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spn.profile.Msg/DisableCoordinator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableCoordinator(ctx, req.(*MsgDisableCoordinator))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spn.profile.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateValidatorDescription",
			Handler:    _Msg_UpdateValidatorDescription_Handler,
		},
		{
			MethodName: "AddValidatorOperatorAddress",
			Handler:    _Msg_AddValidatorOperatorAddress_Handler,
		},
		{
			MethodName: "CreateCoordinator",
			Handler:    _Msg_CreateCoordinator_Handler,
		},
		{
			MethodName: "UpdateCoordinatorDescription",
			Handler:    _Msg_UpdateCoordinatorDescription_Handler,
		},
		{
			MethodName: "UpdateCoordinatorAddress",
			Handler:    _Msg_UpdateCoordinatorAddress_Handler,
		},
		{
			MethodName: "DisableCoordinator",
			Handler:    _Msg_DisableCoordinator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spn/profile/tx.proto",
}

func (m *MsgUpdateValidatorDescription) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateValidatorDescription) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateValidatorDescription) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateValidatorDescriptionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateValidatorDescriptionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateValidatorDescriptionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddValidatorOperatorAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddValidatorOperatorAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddValidatorOperatorAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddValidatorOperatorAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddValidatorOperatorAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddValidatorOperatorAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateCoordinator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCoordinator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCoordinator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCoordinatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCoordinatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCoordinatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CoordinatorID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CoordinatorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCoordinatorDescription) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCoordinatorDescription) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCoordinatorDescription) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCoordinatorDescriptionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCoordinatorDescriptionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCoordinatorDescriptionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCoordinatorAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCoordinatorAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCoordinatorAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewAddress) > 0 {
		i -= len(m.NewAddress)
		copy(dAtA[i:], m.NewAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCoordinatorAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCoordinatorAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCoordinatorAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDisableCoordinator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableCoordinator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableCoordinator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDisableCoordinatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableCoordinatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableCoordinatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CoordinatorID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CoordinatorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateValidatorDescription) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Description.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateValidatorDescriptionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddValidatorOperatorAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddValidatorOperatorAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateCoordinator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Description.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateCoordinatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CoordinatorID != 0 {
		n += 1 + sovTx(uint64(m.CoordinatorID))
	}
	return n
}

func (m *MsgUpdateCoordinatorDescription) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Description.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateCoordinatorDescriptionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCoordinatorAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateCoordinatorAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDisableCoordinator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDisableCoordinatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CoordinatorID != 0 {
		n += 1 + sovTx(uint64(m.CoordinatorID))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateValidatorDescription) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateValidatorDescription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateValidatorDescription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateValidatorDescriptionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateValidatorDescriptionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateValidatorDescriptionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddValidatorOperatorAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddValidatorOperatorAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddValidatorOperatorAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddValidatorOperatorAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddValidatorOperatorAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddValidatorOperatorAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCoordinator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCoordinator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCoordinator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCoordinatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCoordinatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCoordinatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoordinatorID", wireType)
			}
			m.CoordinatorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoordinatorID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCoordinatorDescription) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorDescription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorDescription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCoordinatorDescriptionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorDescriptionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorDescriptionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCoordinatorAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCoordinatorAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCoordinatorAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableCoordinator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableCoordinator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableCoordinator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableCoordinatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableCoordinatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableCoordinatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoordinatorID", wireType)
			}
			m.CoordinatorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoordinatorID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
