// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: participation/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	AllocationPrice       AllocationPrice `protobuf:"bytes,1,opt,name=allocationPrice,proto3" json:"allocationPrice"`
	ParticipationTierList []Tier          `protobuf:"bytes,2,rep,name=participationTierList,proto3" json:"participationTierList"`
	// Time frame in seconds before auction start where MsgParticipate can be called
	RegistrationPeriod int64 `protobuf:"varint,3,opt,name=registrationPeriod,proto3" json:"registrationPeriod,omitempty"`
	// Delay in seconds after auction start when allocations can be withdrawn
	WithdrawalDelay int64 `protobuf:"varint,4,opt,name=withdrawalDelay,proto3" json:"withdrawalDelay,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1941a0f9399e39d9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAllocationPrice() AllocationPrice {
	if m != nil {
		return m.AllocationPrice
	}
	return AllocationPrice{}
}

func (m *Params) GetParticipationTierList() []Tier {
	if m != nil {
		return m.ParticipationTierList
	}
	return nil
}

func (m *Params) GetRegistrationPeriod() int64 {
	if m != nil {
		return m.RegistrationPeriod
	}
	return 0
}

func (m *Params) GetWithdrawalDelay() int64 {
	if m != nil {
		return m.WithdrawalDelay
	}
	return 0
}

type AllocationPrice struct {
	// number of bonded tokens necessary to get one allocation
	Bonded github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=bonded,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"bonded"`
}

func (m *AllocationPrice) Reset()         { *m = AllocationPrice{} }
func (m *AllocationPrice) String() string { return proto.CompactTextString(m) }
func (*AllocationPrice) ProtoMessage()    {}
func (*AllocationPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_1941a0f9399e39d9, []int{1}
}
func (m *AllocationPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllocationPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllocationPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllocationPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocationPrice.Merge(m, src)
}
func (m *AllocationPrice) XXX_Size() int {
	return m.Size()
}
func (m *AllocationPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocationPrice.DiscardUnknown(m)
}

var xxx_messageInfo_AllocationPrice proto.InternalMessageInfo

// Matches a number of required allocations with benefits
type Tier struct {
	TierID              uint64       `protobuf:"varint,1,opt,name=tierID,proto3" json:"tierID,omitempty"`
	RequiredAllocations uint64       `protobuf:"varint,2,opt,name=requiredAllocations,proto3" json:"requiredAllocations,omitempty"`
	Benefits            TierBenefits `protobuf:"bytes,3,opt,name=benefits,proto3" json:"benefits"`
}

func (m *Tier) Reset()         { *m = Tier{} }
func (m *Tier) String() string { return proto.CompactTextString(m) }
func (*Tier) ProtoMessage()    {}
func (*Tier) Descriptor() ([]byte, []int) {
	return fileDescriptor_1941a0f9399e39d9, []int{2}
}
func (m *Tier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tier.Merge(m, src)
}
func (m *Tier) XXX_Size() int {
	return m.Size()
}
func (m *Tier) XXX_DiscardUnknown() {
	xxx_messageInfo_Tier.DiscardUnknown(m)
}

var xxx_messageInfo_Tier proto.InternalMessageInfo

func (m *Tier) GetTierID() uint64 {
	if m != nil {
		return m.TierID
	}
	return 0
}

func (m *Tier) GetRequiredAllocations() uint64 {
	if m != nil {
		return m.RequiredAllocations
	}
	return 0
}

func (m *Tier) GetBenefits() TierBenefits {
	if m != nil {
		return m.Benefits
	}
	return TierBenefits{}
}

type TierBenefits struct {
	// maximum amount an auction participant can bid
	MaxBidAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=maxBidAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"maxBidAmount"`
}

func (m *TierBenefits) Reset()         { *m = TierBenefits{} }
func (m *TierBenefits) String() string { return proto.CompactTextString(m) }
func (*TierBenefits) ProtoMessage()    {}
func (*TierBenefits) Descriptor() ([]byte, []int) {
	return fileDescriptor_1941a0f9399e39d9, []int{3}
}
func (m *TierBenefits) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TierBenefits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TierBenefits.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TierBenefits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TierBenefits.Merge(m, src)
}
func (m *TierBenefits) XXX_Size() int {
	return m.Size()
}
func (m *TierBenefits) XXX_DiscardUnknown() {
	xxx_messageInfo_TierBenefits.DiscardUnknown(m)
}

var xxx_messageInfo_TierBenefits proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "tendermint.spn.participation.Params")
	proto.RegisterType((*AllocationPrice)(nil), "tendermint.spn.participation.AllocationPrice")
	proto.RegisterType((*Tier)(nil), "tendermint.spn.participation.Tier")
	proto.RegisterType((*TierBenefits)(nil), "tendermint.spn.participation.TierBenefits")
}

func init() { proto.RegisterFile("participation/params.proto", fileDescriptor_1941a0f9399e39d9) }

var fileDescriptor_1941a0f9399e39d9 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x8b, 0xd3, 0x40,
	0x1c, 0xc6, 0x93, 0x36, 0x04, 0x9d, 0x2e, 0x14, 0xc6, 0x17, 0xc2, 0x22, 0x69, 0xc9, 0x41, 0x82,
	0xb0, 0x33, 0x52, 0x6f, 0xde, 0x36, 0x2c, 0x42, 0x61, 0x0f, 0x4b, 0xf0, 0xa2, 0xa0, 0x30, 0xc9,
	0x8c, 0xd9, 0xc1, 0x64, 0x26, 0xce, 0x4c, 0xd9, 0xdd, 0x6f, 0xe1, 0xd1, 0x93, 0x78, 0xf3, 0xab,
	0xf4, 0xd8, 0xa3, 0x78, 0x28, 0xd2, 0x7e, 0x11, 0xc9, 0x34, 0xd8, 0xa6, 0x94, 0x22, 0x7b, 0xca,
	0xcb, 0xff, 0x79, 0x7e, 0xf3, 0x7f, 0x1e, 0x12, 0x70, 0x5a, 0x13, 0x65, 0x78, 0xce, 0x6b, 0x62,
	0xb8, 0x14, 0xb8, 0x26, 0x8a, 0x54, 0x1a, 0xd5, 0x4a, 0x1a, 0x09, 0x9f, 0x19, 0x26, 0x28, 0x53,
	0x15, 0x17, 0x06, 0xe9, 0x5a, 0xa0, 0x8e, 0xf4, 0xf4, 0x71, 0x21, 0x0b, 0x69, 0x85, 0xb8, 0xb9,
	0xdb, 0x78, 0xa2, 0x9f, 0x3d, 0xe0, 0x5f, 0x59, 0x08, 0xfc, 0x00, 0x86, 0xa4, 0x2c, 0x65, 0x6e,
	0xe5, 0x57, 0x8a, 0xe7, 0x2c, 0x70, 0xc7, 0x6e, 0x3c, 0x98, 0x9c, 0xa1, 0x63, 0x60, 0x74, 0xde,
	0x35, 0x25, 0xde, 0x7c, 0x39, 0x72, 0xd2, 0x7d, 0x16, 0xfc, 0x08, 0x9e, 0x74, 0x7c, 0x6f, 0x39,
	0x53, 0x97, 0x5c, 0x9b, 0xa0, 0x37, 0xee, 0xc7, 0x83, 0x49, 0x74, 0xfc, 0x90, 0x46, 0xdd, 0x92,
	0x0f, 0x63, 0x20, 0x02, 0x50, 0xb1, 0x82, 0x6b, 0xa3, 0x36, 0x87, 0x32, 0xc5, 0x25, 0x0d, 0xfa,
	0x63, 0x37, 0xee, 0xa7, 0x07, 0x26, 0x30, 0x06, 0xc3, 0x1b, 0x6e, 0xae, 0xa9, 0x22, 0x37, 0xa4,
	0xbc, 0x60, 0x25, 0xb9, 0x0b, 0x3c, 0x2b, 0xde, 0x7f, 0xfd, 0xda, 0xfb, 0xf6, 0x63, 0xe4, 0x44,
	0xef, 0xc0, 0x70, 0x2f, 0x29, 0x7c, 0x03, 0xfc, 0x4c, 0x0a, 0xca, 0xa8, 0x2d, 0xea, 0x61, 0x82,
	0x9a, 0xfd, 0x7e, 0x2f, 0x47, 0xcf, 0x0b, 0x6e, 0xae, 0x67, 0x19, 0xca, 0x65, 0x85, 0x73, 0xa9,
	0x2b, 0xa9, 0xdb, 0xcb, 0x99, 0xa6, 0x9f, 0xb1, 0xb9, 0xab, 0x99, 0x46, 0x53, 0x61, 0xd2, 0xd6,
	0x1d, 0x7d, 0x77, 0x81, 0xd7, 0xe4, 0x80, 0x4f, 0x81, 0x6f, 0x38, 0x53, 0xd3, 0x0b, 0x0b, 0xf4,
	0xd2, 0xf6, 0x09, 0xbe, 0x04, 0x8f, 0x14, 0xfb, 0x32, 0xe3, 0x8a, 0xd1, 0xed, 0x0e, 0x3a, 0xe8,
	0x59, 0xd1, 0xa1, 0x11, 0xbc, 0x04, 0x0f, 0x32, 0x26, 0xd8, 0x27, 0x6e, 0xb4, 0xed, 0x60, 0x30,
	0x79, 0xf1, 0x1f, 0x05, 0xb7, 0x8e, 0xb6, 0xe8, 0x7f, 0x84, 0x28, 0x03, 0x27, 0xbb, 0x73, 0x98,
	0x82, 0x93, 0x8a, 0xdc, 0x26, 0x9c, 0x9e, 0x57, 0x72, 0x26, 0xcc, 0x3d, 0xe3, 0x77, 0x18, 0xc9,
	0x74, 0xbe, 0x0a, 0xdd, 0xc5, 0x2a, 0x74, 0xff, 0xac, 0x42, 0xf7, 0xeb, 0x3a, 0x74, 0x16, 0xeb,
	0xd0, 0xf9, 0xb5, 0x0e, 0x9d, 0xf7, 0x78, 0x87, 0xb7, 0xcd, 0x80, 0x75, 0x2d, 0xf0, 0x2d, 0xee,
	0xfe, 0x0f, 0x16, 0x9e, 0xf9, 0xf6, 0xdb, 0x7e, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x83, 0x9c,
	0xe4, 0x75, 0x2d, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WithdrawalDelay != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WithdrawalDelay))
		i--
		dAtA[i] = 0x20
	}
	if m.RegistrationPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RegistrationPeriod))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ParticipationTierList) > 0 {
		for iNdEx := len(m.ParticipationTierList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ParticipationTierList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.AllocationPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AllocationPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllocationPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllocationPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Bonded.Size()
		i -= size
		if _, err := m.Bonded.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Tier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Benefits.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.RequiredAllocations != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RequiredAllocations))
		i--
		dAtA[i] = 0x10
	}
	if m.TierID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TierID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TierBenefits) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TierBenefits) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TierBenefits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxBidAmount.Size()
		i -= size
		if _, err := m.MaxBidAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AllocationPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.ParticipationTierList) > 0 {
		for _, e := range m.ParticipationTierList {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.RegistrationPeriod != 0 {
		n += 1 + sovParams(uint64(m.RegistrationPeriod))
	}
	if m.WithdrawalDelay != 0 {
		n += 1 + sovParams(uint64(m.WithdrawalDelay))
	}
	return n
}

func (m *AllocationPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Bonded.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Tier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TierID != 0 {
		n += 1 + sovParams(uint64(m.TierID))
	}
	if m.RequiredAllocations != 0 {
		n += 1 + sovParams(uint64(m.RequiredAllocations))
	}
	l = m.Benefits.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *TierBenefits) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MaxBidAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocationPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AllocationPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipationTierList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipationTierList = append(m.ParticipationTierList, Tier{})
			if err := m.ParticipationTierList[len(m.ParticipationTierList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationPeriod", wireType)
			}
			m.RegistrationPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalDelay", wireType)
			}
			m.WithdrawalDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalDelay |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllocationPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllocationPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllocationPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bonded", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bonded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TierID", wireType)
			}
			m.TierID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TierID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredAllocations", wireType)
			}
			m.RequiredAllocations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredAllocations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Benefits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Benefits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TierBenefits) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TierBenefits: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TierBenefits: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBidAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBidAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
