// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: launch/chain.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainNameCount struct {
	ChainName string `protobuf:"bytes,1,opt,name=chainName,proto3" json:"chainName,omitempty"`
	Count     uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *ChainNameCount) Reset()         { *m = ChainNameCount{} }
func (m *ChainNameCount) String() string { return proto.CompactTextString(m) }
func (*ChainNameCount) ProtoMessage()    {}
func (*ChainNameCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_36e96f39bc2e1bde, []int{0}
}
func (m *ChainNameCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainNameCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainNameCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainNameCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainNameCount.Merge(m, src)
}
func (m *ChainNameCount) XXX_Size() int {
	return m.Size()
}
func (m *ChainNameCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainNameCount.DiscardUnknown(m)
}

var xxx_messageInfo_ChainNameCount proto.InternalMessageInfo

func (m *ChainNameCount) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *ChainNameCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Chain struct {
	Id              uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CoordinatorID   uint64         `protobuf:"varint,2,opt,name=coordinatorID,proto3" json:"coordinatorID,omitempty"`
	GenesisChainID  string         `protobuf:"bytes,3,opt,name=genesisChainID,proto3" json:"genesisChainID,omitempty"`
	CreatedAt       int64          `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	SourceURL       string         `protobuf:"bytes,5,opt,name=sourceURL,proto3" json:"sourceURL,omitempty"`
	SourceHash      string         `protobuf:"bytes,6,opt,name=sourceHash,proto3" json:"sourceHash,omitempty"`
	InitialGenesis  InitialGenesis `protobuf:"bytes,7,opt,name=initialGenesis,proto3" json:"initialGenesis"`
	HasCampaign     bool           `protobuf:"varint,8,opt,name=hasCampaign,proto3" json:"hasCampaign,omitempty"`
	CampaignID      uint64         `protobuf:"varint,9,opt,name=campaignID,proto3" json:"campaignID,omitempty"`
	IsMainnet       bool           `protobuf:"varint,10,opt,name=isMainnet,proto3" json:"isMainnet,omitempty"`
	LaunchTriggered bool           `protobuf:"varint,11,opt,name=launchTriggered,proto3" json:"launchTriggered,omitempty"`
	LaunchTimestamp int64          `protobuf:"varint,12,opt,name=launchTimestamp,proto3" json:"launchTimestamp,omitempty"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_36e96f39bc2e1bde, []int{1}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return m.Size()
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chain) GetCoordinatorID() uint64 {
	if m != nil {
		return m.CoordinatorID
	}
	return 0
}

func (m *Chain) GetGenesisChainID() string {
	if m != nil {
		return m.GenesisChainID
	}
	return ""
}

func (m *Chain) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Chain) GetSourceURL() string {
	if m != nil {
		return m.SourceURL
	}
	return ""
}

func (m *Chain) GetSourceHash() string {
	if m != nil {
		return m.SourceHash
	}
	return ""
}

func (m *Chain) GetInitialGenesis() InitialGenesis {
	if m != nil {
		return m.InitialGenesis
	}
	return InitialGenesis{}
}

func (m *Chain) GetHasCampaign() bool {
	if m != nil {
		return m.HasCampaign
	}
	return false
}

func (m *Chain) GetCampaignID() uint64 {
	if m != nil {
		return m.CampaignID
	}
	return 0
}

func (m *Chain) GetIsMainnet() bool {
	if m != nil {
		return m.IsMainnet
	}
	return false
}

func (m *Chain) GetLaunchTriggered() bool {
	if m != nil {
		return m.LaunchTriggered
	}
	return false
}

func (m *Chain) GetLaunchTimestamp() int64 {
	if m != nil {
		return m.LaunchTimestamp
	}
	return 0
}

type InitialGenesis struct {
	// Types that are valid to be assigned to Source:
	//	*InitialGenesis_DefaultInitialGenesis
	//	*InitialGenesis_GenesisURL
	Source isInitialGenesis_Source `protobuf_oneof:"source"`
}

func (m *InitialGenesis) Reset()         { *m = InitialGenesis{} }
func (m *InitialGenesis) String() string { return proto.CompactTextString(m) }
func (*InitialGenesis) ProtoMessage()    {}
func (*InitialGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_36e96f39bc2e1bde, []int{2}
}
func (m *InitialGenesis) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InitialGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InitialGenesis.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InitialGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialGenesis.Merge(m, src)
}
func (m *InitialGenesis) XXX_Size() int {
	return m.Size()
}
func (m *InitialGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_InitialGenesis proto.InternalMessageInfo

type isInitialGenesis_Source interface {
	isInitialGenesis_Source()
	MarshalTo([]byte) (int, error)
	Size() int
}

type InitialGenesis_DefaultInitialGenesis struct {
	DefaultInitialGenesis *DefaultInitialGenesis `protobuf:"bytes,1,opt,name=defaultInitialGenesis,proto3,oneof" json:"defaultInitialGenesis,omitempty"`
}
type InitialGenesis_GenesisURL struct {
	GenesisURL *GenesisURL `protobuf:"bytes,2,opt,name=genesisURL,proto3,oneof" json:"genesisURL,omitempty"`
}

func (*InitialGenesis_DefaultInitialGenesis) isInitialGenesis_Source() {}
func (*InitialGenesis_GenesisURL) isInitialGenesis_Source()            {}

func (m *InitialGenesis) GetSource() isInitialGenesis_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *InitialGenesis) GetDefaultInitialGenesis() *DefaultInitialGenesis {
	if x, ok := m.GetSource().(*InitialGenesis_DefaultInitialGenesis); ok {
		return x.DefaultInitialGenesis
	}
	return nil
}

func (m *InitialGenesis) GetGenesisURL() *GenesisURL {
	if x, ok := m.GetSource().(*InitialGenesis_GenesisURL); ok {
		return x.GenesisURL
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InitialGenesis) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InitialGenesis_DefaultInitialGenesis)(nil),
		(*InitialGenesis_GenesisURL)(nil),
	}
}

// DefaultInitialGenesis specifies using the default CLI-generated genesis as an initial genesis
type DefaultInitialGenesis struct {
}

func (m *DefaultInitialGenesis) Reset()         { *m = DefaultInitialGenesis{} }
func (m *DefaultInitialGenesis) String() string { return proto.CompactTextString(m) }
func (*DefaultInitialGenesis) ProtoMessage()    {}
func (*DefaultInitialGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_36e96f39bc2e1bde, []int{3}
}
func (m *DefaultInitialGenesis) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DefaultInitialGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DefaultInitialGenesis.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DefaultInitialGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultInitialGenesis.Merge(m, src)
}
func (m *DefaultInitialGenesis) XXX_Size() int {
	return m.Size()
}
func (m *DefaultInitialGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultInitialGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultInitialGenesis proto.InternalMessageInfo

// GenesisURL specifies using a custom genesis from a URL as the initial genesis
type GenesisURL struct {
	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GenesisURL) Reset()         { *m = GenesisURL{} }
func (m *GenesisURL) String() string { return proto.CompactTextString(m) }
func (*GenesisURL) ProtoMessage()    {}
func (*GenesisURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_36e96f39bc2e1bde, []int{4}
}
func (m *GenesisURL) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisURL.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisURL.Merge(m, src)
}
func (m *GenesisURL) XXX_Size() int {
	return m.Size()
}
func (m *GenesisURL) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisURL.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisURL proto.InternalMessageInfo

func (m *GenesisURL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GenesisURL) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*ChainNameCount)(nil), "tendermint.spn.launch.ChainNameCount")
	proto.RegisterType((*Chain)(nil), "tendermint.spn.launch.Chain")
	proto.RegisterType((*InitialGenesis)(nil), "tendermint.spn.launch.InitialGenesis")
	proto.RegisterType((*DefaultInitialGenesis)(nil), "tendermint.spn.launch.DefaultInitialGenesis")
	proto.RegisterType((*GenesisURL)(nil), "tendermint.spn.launch.GenesisURL")
}

func init() { proto.RegisterFile("launch/chain.proto", fileDescriptor_36e96f39bc2e1bde) }

var fileDescriptor_36e96f39bc2e1bde = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xe3, 0xfe, 0xa3, 0x9d, 0x42, 0x41, 0xd6, 0x56, 0x58, 0x08, 0x85, 0x50, 0x01, 0xca,
	0x01, 0x25, 0x52, 0x79, 0x02, 0xda, 0x48, 0xdb, 0x4a, 0xc0, 0x21, 0xc0, 0x85, 0x9b, 0x37, 0x31,
	0x89, 0xa5, 0xc6, 0x8e, 0x62, 0x47, 0x82, 0xb7, 0xe0, 0xa5, 0x90, 0x56, 0x9c, 0xf6, 0xc8, 0x09,
	0xa1, 0xf6, 0x45, 0x50, 0x9c, 0xb0, 0x49, 0xab, 0xee, 0x6d, 0xfc, 0xf3, 0xf7, 0x8d, 0xc7, 0x33,
	0x36, 0xe0, 0x1d, 0x2d, 0x45, 0x94, 0xfa, 0x51, 0x4a, 0xb9, 0xf0, 0xf2, 0x42, 0x6a, 0x89, 0xe7,
	0x9a, 0x89, 0x98, 0x15, 0x19, 0x17, 0xda, 0x53, 0xb9, 0xf0, 0x6a, 0xc9, 0x93, 0x8b, 0x44, 0x26,
	0xd2, 0x28, 0xfc, 0x2a, 0xaa, 0xc5, 0x8b, 0x00, 0x66, 0xeb, 0xca, 0xfb, 0x81, 0x66, 0x6c, 0x2d,
	0x4b, 0xa1, 0xf1, 0x53, 0x98, 0x44, 0xff, 0x09, 0x41, 0x0e, 0x72, 0x27, 0x61, 0x0b, 0xf0, 0x05,
	0x0c, 0xa3, 0x4a, 0x46, 0x7a, 0x0e, 0x72, 0x07, 0x61, 0xbd, 0x58, 0xfc, 0xea, 0xc3, 0xd0, 0xa4,
	0xc1, 0x33, 0xe8, 0xf1, 0xd8, 0xd8, 0x06, 0x61, 0x8f, 0xc7, 0xf8, 0x05, 0x3c, 0x88, 0xa4, 0x2c,
	0x62, 0x2e, 0xa8, 0x96, 0xc5, 0x36, 0x68, 0x7c, 0xc7, 0x10, 0xbf, 0x82, 0x59, 0xc2, 0x04, 0x53,
	0x5c, 0x99, 0x2c, 0xdb, 0x80, 0xf4, 0xcd, 0xc1, 0x27, 0xd4, 0xd4, 0x56, 0x30, 0xaa, 0x59, 0xfc,
	0x56, 0x93, 0x81, 0x83, 0xdc, 0x7e, 0xd8, 0x82, 0x6a, 0x57, 0xc9, 0xb2, 0x88, 0xd8, 0xe7, 0xf0,
	0x1d, 0x19, 0xd6, 0x95, 0xdf, 0x02, 0x6c, 0x03, 0xd4, 0x8b, 0x0d, 0x55, 0x29, 0x19, 0x99, 0xed,
	0x0e, 0xc1, 0x1f, 0x61, 0xc6, 0x05, 0xd7, 0x9c, 0xee, 0x2e, 0xeb, 0x43, 0xc9, 0x3d, 0x07, 0xb9,
	0xd3, 0xe5, 0x4b, 0xef, 0x6c, 0x3f, 0xbd, 0xed, 0x91, 0x78, 0x35, 0xb8, 0xfe, 0xf3, 0xcc, 0x0a,
	0x4f, 0x52, 0x60, 0x07, 0xa6, 0x29, 0x55, 0x6b, 0x9a, 0xe5, 0x94, 0x27, 0x82, 0x8c, 0x1d, 0xe4,
	0x8e, 0xc3, 0x2e, 0xaa, 0xca, 0x8a, 0x9a, 0x78, 0x1b, 0x90, 0x89, 0xe9, 0x4e, 0x87, 0x54, 0x97,
	0xe2, 0xea, 0x3d, 0xe5, 0x42, 0x30, 0x4d, 0xc0, 0xf8, 0x5b, 0x80, 0x5d, 0x78, 0x58, 0x97, 0xf3,
	0xa9, 0xe0, 0x49, 0xc2, 0x0a, 0x16, 0x93, 0xa9, 0xd1, 0x9c, 0xe2, 0x8e, 0x92, 0x67, 0x4c, 0x69,
	0x9a, 0xe5, 0xe4, 0xbe, 0x69, 0xe0, 0x29, 0x5e, 0xfc, 0x44, 0x30, 0x3b, 0xbe, 0x1c, 0x8e, 0x61,
	0x1e, 0xb3, 0xaf, 0xb4, 0xdc, 0xe9, 0xe3, 0x0d, 0x33, 0xe8, 0xe9, 0xf2, 0xf5, 0x1d, 0x2d, 0x0a,
	0xce, 0x79, 0x36, 0x56, 0x78, 0x3e, 0x19, 0x5e, 0x03, 0x34, 0xf3, 0xae, 0x06, 0xd8, 0x33, 0xa9,
	0x9f, 0xdf, 0x91, 0xfa, 0xf2, 0x56, 0xb8, 0xb1, 0xc2, 0x8e, 0x6d, 0x35, 0x86, 0x51, 0x3d, 0xd4,
	0xc5, 0x63, 0x98, 0x9f, 0x2d, 0x60, 0xb1, 0x04, 0x68, 0xed, 0xf8, 0x11, 0xf4, 0xcb, 0x62, 0xd7,
	0xbc, 0xf4, 0x2a, 0xc4, 0x18, 0x06, 0x69, 0xf5, 0x46, 0x7a, 0x06, 0x99, 0x78, 0xb5, 0xba, 0xde,
	0xdb, 0xe8, 0x66, 0x6f, 0xa3, 0xbf, 0x7b, 0x1b, 0xfd, 0x38, 0xd8, 0xd6, 0xcd, 0xc1, 0xb6, 0x7e,
	0x1f, 0x6c, 0xeb, 0x8b, 0x9b, 0x70, 0x9d, 0x96, 0x57, 0x5e, 0x24, 0x33, 0xbf, 0xad, 0xd5, 0x57,
	0xb9, 0xf0, 0xbf, 0xf9, 0xcd, 0xf7, 0xd4, 0xdf, 0x73, 0xa6, 0xae, 0x46, 0xe6, 0xcb, 0xbd, 0xf9,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x97, 0x3d, 0xb6, 0xb5, 0x03, 0x00, 0x00,
}

func (m *ChainNameCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainNameCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainNameCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintChain(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Chain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaunchTimestamp != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.LaunchTimestamp))
		i--
		dAtA[i] = 0x60
	}
	if m.LaunchTriggered {
		i--
		if m.LaunchTriggered {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.IsMainnet {
		i--
		if m.IsMainnet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.CampaignID != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.CampaignID))
		i--
		dAtA[i] = 0x48
	}
	if m.HasCampaign {
		i--
		if m.HasCampaign {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.InitialGenesis.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintChain(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.SourceHash) > 0 {
		i -= len(m.SourceHash)
		copy(dAtA[i:], m.SourceHash)
		i = encodeVarintChain(dAtA, i, uint64(len(m.SourceHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SourceURL) > 0 {
		i -= len(m.SourceURL)
		copy(dAtA[i:], m.SourceURL)
		i = encodeVarintChain(dAtA, i, uint64(len(m.SourceURL)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.GenesisChainID) > 0 {
		i -= len(m.GenesisChainID)
		copy(dAtA[i:], m.GenesisChainID)
		i = encodeVarintChain(dAtA, i, uint64(len(m.GenesisChainID)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CoordinatorID != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.CoordinatorID))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InitialGenesis) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitialGenesis) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Source != nil {
		{
			size := m.Source.Size()
			i -= size
			if _, err := m.Source.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *InitialGenesis_DefaultInitialGenesis) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis_DefaultInitialGenesis) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DefaultInitialGenesis != nil {
		{
			size, err := m.DefaultInitialGenesis.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *InitialGenesis_GenesisURL) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis_GenesisURL) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GenesisURL != nil {
		{
			size, err := m.GenesisURL.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *DefaultInitialGenesis) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DefaultInitialGenesis) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DefaultInitialGenesis) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GenesisURL) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisURL) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisURL) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChain(dAtA []byte, offset int, v uint64) int {
	offset -= sovChain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainNameCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovChain(uint64(m.Count))
	}
	return n
}

func (m *Chain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovChain(uint64(m.Id))
	}
	if m.CoordinatorID != 0 {
		n += 1 + sovChain(uint64(m.CoordinatorID))
	}
	l = len(m.GenesisChainID)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovChain(uint64(m.CreatedAt))
	}
	l = len(m.SourceURL)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.SourceHash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = m.InitialGenesis.Size()
	n += 1 + l + sovChain(uint64(l))
	if m.HasCampaign {
		n += 2
	}
	if m.CampaignID != 0 {
		n += 1 + sovChain(uint64(m.CampaignID))
	}
	if m.IsMainnet {
		n += 2
	}
	if m.LaunchTriggered {
		n += 2
	}
	if m.LaunchTimestamp != 0 {
		n += 1 + sovChain(uint64(m.LaunchTimestamp))
	}
	return n
}

func (m *InitialGenesis) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Source != nil {
		n += m.Source.Size()
	}
	return n
}

func (m *InitialGenesis_DefaultInitialGenesis) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DefaultInitialGenesis != nil {
		l = m.DefaultInitialGenesis.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}
func (m *InitialGenesis_GenesisURL) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GenesisURL != nil {
		l = m.GenesisURL.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}
func (m *DefaultInitialGenesis) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GenesisURL) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func sovChain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChain(x uint64) (n int) {
	return sovChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainNameCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainNameCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainNameCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Chain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoordinatorID", wireType)
			}
			m.CoordinatorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoordinatorID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialGenesis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialGenesis.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasCampaign", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasCampaign = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignID", wireType)
			}
			m.CampaignID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMainnet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMainnet = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchTriggered", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LaunchTriggered = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchTimestamp", wireType)
			}
			m.LaunchTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitialGenesis) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitialGenesis: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitialGenesis: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultInitialGenesis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DefaultInitialGenesis{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Source = &InitialGenesis_DefaultInitialGenesis{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisURL", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GenesisURL{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Source = &InitialGenesis_GenesisURL{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DefaultInitialGenesis) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DefaultInitialGenesis: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DefaultInitialGenesis: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisURL) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisURL: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisURL: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChain = fmt.Errorf("proto: unexpected end of group")
)
