// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: launch/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the staking module.
type Params struct {
	LaunchTimeRange  LaunchTimeRange                          `protobuf:"bytes,1,opt,name=launchTimeRange,proto3" json:"launchTimeRange"`
	RevertDelay      int64                                    `protobuf:"varint,2,opt,name=revertDelay,proto3" json:"revertDelay,omitempty"`
	ChainCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=chainCreationFee,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"chainCreationFee"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f73d6645a211b2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLaunchTimeRange() LaunchTimeRange {
	if m != nil {
		return m.LaunchTimeRange
	}
	return LaunchTimeRange{}
}

func (m *Params) GetRevertDelay() int64 {
	if m != nil {
		return m.RevertDelay
	}
	return 0
}

func (m *Params) GetChainCreationFee() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.ChainCreationFee
	}
	return nil
}

type LaunchTimeRange struct {
	MinLaunchTime time.Duration `protobuf:"bytes,1,opt,name=minLaunchTime,proto3,stdduration" json:"minLaunchTime"`
	MaxLaunchTime time.Duration `protobuf:"bytes,2,opt,name=maxLaunchTime,proto3,stdduration" json:"maxLaunchTime"`
}

func (m *LaunchTimeRange) Reset()         { *m = LaunchTimeRange{} }
func (m *LaunchTimeRange) String() string { return proto.CompactTextString(m) }
func (*LaunchTimeRange) ProtoMessage()    {}
func (*LaunchTimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f73d6645a211b2, []int{1}
}
func (m *LaunchTimeRange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LaunchTimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LaunchTimeRange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LaunchTimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchTimeRange.Merge(m, src)
}
func (m *LaunchTimeRange) XXX_Size() int {
	return m.Size()
}
func (m *LaunchTimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchTimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchTimeRange proto.InternalMessageInfo

func (m *LaunchTimeRange) GetMinLaunchTime() time.Duration {
	if m != nil {
		return m.MinLaunchTime
	}
	return 0
}

func (m *LaunchTimeRange) GetMaxLaunchTime() time.Duration {
	if m != nil {
		return m.MaxLaunchTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "tendermint.spn.launch.Params")
	proto.RegisterType((*LaunchTimeRange)(nil), "tendermint.spn.launch.LaunchTimeRange")
}

func init() { proto.RegisterFile("launch/params.proto", fileDescriptor_b8f73d6645a211b2) }

var fileDescriptor_b8f73d6645a211b2 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbf, 0x6e, 0xda, 0x40,
	0x18, 0xf7, 0x01, 0x42, 0x95, 0x51, 0x45, 0xe5, 0xb6, 0x12, 0x30, 0xd8, 0x16, 0x43, 0xeb, 0xa5,
	0x77, 0x82, 0x6e, 0x1d, 0x0d, 0xaa, 0x54, 0xa9, 0x43, 0x65, 0x55, 0x1d, 0x9a, 0xe9, 0x6c, 0x2e,
	0xe6, 0x14, 0x7c, 0x67, 0xf9, 0xce, 0x08, 0xde, 0x22, 0x23, 0x63, 0x94, 0x25, 0x52, 0xa4, 0xbc,
	0x07, 0x23, 0x63, 0x26, 0x88, 0xe0, 0x2d, 0x32, 0x45, 0x3e, 0x1b, 0x61, 0x48, 0x86, 0x64, 0xb2,
	0x7d, 0xdf, 0xef, 0xfb, 0xfd, 0xf3, 0xe9, 0x1f, 0x27, 0x38, 0x65, 0xc1, 0x18, 0xc5, 0x38, 0xc1,
	0x91, 0x80, 0x71, 0xc2, 0x25, 0x37, 0x3e, 0x4b, 0xc2, 0x46, 0x24, 0x89, 0x28, 0x93, 0x50, 0xc4,
	0x0c, 0xe6, 0x98, 0xce, 0xa7, 0x90, 0x87, 0x5c, 0x21, 0x50, 0xf6, 0x96, 0x83, 0x3b, 0x66, 0xc0,
	0x45, 0xc4, 0x05, 0xf2, 0xb1, 0x20, 0x68, 0xda, 0xf3, 0x89, 0xc4, 0x3d, 0x14, 0x70, 0xca, 0xf6,
	0xf3, 0x90, 0xf3, 0x70, 0x42, 0x90, 0xfa, 0xf2, 0xd3, 0x73, 0x34, 0x4a, 0x13, 0x2c, 0x29, 0x2f,
	0xe6, 0xdd, 0xbb, 0x8a, 0x5e, 0xff, 0xa3, 0xd4, 0x8d, 0x7f, 0x7a, 0x33, 0x97, 0xfa, 0x4b, 0x23,
	0xe2, 0x61, 0x16, 0x92, 0x16, 0xb0, 0x81, 0xd3, 0xe8, 0x7f, 0x81, 0x2f, 0x3a, 0x82, 0xbf, 0x8f,
	0xd1, 0x6e, 0x6d, 0xb9, 0xb6, 0x34, 0xef, 0x94, 0xc4, 0xb0, 0xf5, 0x46, 0x42, 0xa6, 0x24, 0x91,
	0x43, 0x32, 0xc1, 0xf3, 0x56, 0xc5, 0x06, 0x4e, 0xd5, 0x2b, 0x1f, 0x19, 0xd7, 0x40, 0xff, 0x10,
	0x8c, 0x31, 0x65, 0x83, 0x84, 0x28, 0x73, 0x3f, 0x09, 0x69, 0x55, 0xed, 0xaa, 0xd3, 0xe8, 0xb7,
	0x61, 0x1e, 0x10, 0x66, 0x01, 0x61, 0x11, 0x10, 0x0e, 0x38, 0x65, 0xee, 0x59, 0x26, 0xf7, 0xb8,
	0xb6, 0xbe, 0x86, 0x54, 0x8e, 0x53, 0x1f, 0x06, 0x3c, 0x42, 0x45, 0x1b, 0xf9, 0xe3, 0x9b, 0x18,
	0x5d, 0x20, 0x39, 0x8f, 0x89, 0x50, 0x0b, 0xb7, 0x1b, 0xcb, 0x79, 0x25, 0x54, 0x78, 0xcf, 0xfc,
	0xfc, 0xa8, 0x2d, 0xae, 0x2c, 0xad, 0x7b, 0x03, 0xf4, 0xe6, 0x49, 0x6e, 0xe3, 0x97, 0xfe, 0x3e,
	0xa2, 0xec, 0x70, 0x5a, 0xd4, 0xd6, 0x86, 0x79, 0xf7, 0x70, 0xdf, 0x3d, 0x1c, 0x16, 0xdd, 0xbb,
	0xef, 0x32, 0xeb, 0x8b, 0x8d, 0x05, 0xbc, 0xe3, 0x4d, 0x45, 0x85, 0x67, 0x25, 0xaa, 0xca, 0x5b,
	0xa8, 0xca, 0x9b, 0xae, 0xbb, 0xdc, 0x9a, 0x60, 0xb5, 0x35, 0xc1, 0xc3, 0xd6, 0x04, 0x97, 0x3b,
	0x53, 0x5b, 0xed, 0x4c, 0xed, 0x7e, 0x67, 0x6a, 0xff, 0xcb, 0x2d, 0x1c, 0xfe, 0x2c, 0x12, 0x31,
	0x43, 0x33, 0x54, 0xdc, 0x48, 0xd5, 0x85, 0x5f, 0x57, 0x7a, 0xdf, 0x9f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0xcb, 0x53, 0x9c, 0xa8, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainCreationFee) > 0 {
		for iNdEx := len(m.ChainCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChainCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.RevertDelay != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RevertDelay))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.LaunchTimeRange.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *LaunchTimeRange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LaunchTimeRange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LaunchTimeRange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.MaxLaunchTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.MaxLaunchTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.MinLaunchTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.MinLaunchTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LaunchTimeRange.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.RevertDelay != 0 {
		n += 1 + sovParams(uint64(m.RevertDelay))
	}
	if len(m.ChainCreationFee) > 0 {
		for _, e := range m.ChainCreationFee {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *LaunchTimeRange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.MinLaunchTime)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.MaxLaunchTime)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchTimeRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LaunchTimeRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevertDelay", wireType)
			}
			m.RevertDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevertDelay |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainCreationFee = append(m.ChainCreationFee, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.ChainCreationFee[len(m.ChainCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LaunchTimeRange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LaunchTimeRange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LaunchTimeRange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLaunchTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.MinLaunchTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLaunchTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.MaxLaunchTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
