name: 'Dependency Review'
# Dependency Review workflow action scans pull requests for dependency changes and
# will raise an error if any new dependencies have existing vulnerabilities.
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3