name: Simulation Tests

on:
  pull_request:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Run simulation tests
        run: make test-sim-ci
