name: Test-Integration
# Run starport serve

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: go/src/github.com/tendermint/spn

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install protoc
        uses: arduino/setup-protoc@v1

      - name: Install protoc-gen-gocosmos
        run: go get github.com/regen-network/cosmos-proto/protoc-gen-gocosmos

      - name: Set up packr2
        run: go get -u github.com/gobuffalo/packr/v2/packr2

      - name: Set up relayer
        run: git clone https://github.com/ovrclk/relayer && cd relayer && git checkout 3080dab10e37e6db9e691c343b1c0cdb6d845753 && make install

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Install Starport
        working-directory: ${{ env.working-directory }}
        run: |
          git clone https://github.com/tendermint/starport && cd starport && go install ./...

      - name: Run Integration Tests
        working-directory: ${{ env.working-directory }}
        run: ./scripts/test-integration 
